# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: tribulus.marketplace
services:
- name: authserver
  project: apps/auth-server/Tribulus.MarketPlace.AuthServer.csproj
  bindings:
     - protocol: https
       port: 44351
- name: admingateway
  project: gateways/admin-gateway/Tribulus.MarketPlace.AdminGateway.csproj
  bindings:
     - protocol: https
       port: 44354
- name: publicgateway
  project: gateways/public-gateway/Tribulus.MarketPlace.PublicGateway.csproj
  bindings:
     - protocol: https
       port: 44311
- name: abp-service
  project: modules/abp/host/Tribulus.MarketPlace.AbpService.HttpApi.Host/Tribulus.MarketPlace.AbpService.HttpApi.Host.csproj
  bindings:
     - protocol: https
       port: 44373
- name: admin-inventory-service
  project: modules/inventory/host/Tribulus.MarketPlace.Admin.Inventory.HttpApi.Host/Tribulus.MarketPlace.Admin.Inventory.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44393
- name: admin-marketing-service
  project: modules/marketing/host/Tribulus.MarketPlace.Admin.Marketing.HttpApi.Host/Tribulus.MarketPlace.Admin.Marketing.HttpApi.Host.csproj
  bindings:
     - protocol: https
       port: 44361
- name: admin-sales-service
  project: modules/sales/host/Tribulus.MarketPlace.Admin.Sales.HttpApi.Host/Tribulus.MarketPlace.Admin.Sales.HttpApi.Host.csproj
  bindings:
     - protocol: https
       port: 44371
- name: aggregate-service
  project: modules/aggregate/host/Tribulus.MarketPlace.AggregateService.HttpApi.Host/Tribulus.MarketPlace.AggregateService.HttpApi.Host.csproj
  bindings:
       - protocol: https
         port: 44397
- name: redis
  image: redis
  bindings:
  - port: 6380
    containerPort: 6379
    connectionString: "${host}:${port}" 
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"

